### ISSUE TITLE
Issue with inference

### ISSUE THREAD

**Issue by corranmac** [BrightGu/MediumVC#2]
Hi there, I feel I have my folders set up correctly and dependencies installed, hence an output folder is generated at the start of the inference, however shortly after starting I receive the error:

11/04 03:09:35 AM (Elapsed: 00:00:04) loading the model from Any2Any/model/checkpoint-3900.pt
11/04 03:09:36 AM (Elapsed: 00:00:04) config = {'hifi_model_path': 'hifivoice/pretrained/UNIVERSAL_V1/g_02500000', 'hifi_config_path': 'hifivoice/pretrained/UNIVERSAL_V1/config.json', 'wav2mel_model_path': 'Any2Any/model/dvector/pre_model/wav2mel.pt', 'dvector_model_path': 'Any2Any/model/dvector/pre_model/dvector-step250000.pt', 'pre_train_singlevc': True, 'singlevc_model_path': 'Any2Any/model/checkpoint-3000.pt', 'test_wav_dir': 'Any2Any/audio/in/', 'out_dir': 'Any2Any/audio/out/', 'batch_size': 1, 'resume_path': 'Any2Any/model/checkpoint-3900.pt', 'num_mels': 80, 'num_freq': 1025, 'n_fft': 1024, 'hop_size': 256, 'win_size': 1024, 'sampling_rate': 22050, 'fmin': 0, 'fmax': 8000, 'num_workers': 1}
param Generator size = 26.418132M 
Traceback (most recent call last):
  File "Any2Any/infer/infer.py", line 96, in <module>
    solver.infer()
  File "Any2Any/infer/infer.py", line 60, in infer
    test_data_loader = self.get_test_data_loaders()
  File "Any2Any/infer/infer.py", line 43, in get_test_data_loaders
    test_filelist = get_infer_dataset_filelist(self.config["test_wav_dir"])
  File "/content/drive/MyDrive/MediumVC/Any2Any/meldataset.py", line 109, in get_infer_dataset_filelist
    source_file = random.choice(source_file_list)
  File "/usr/lib/python3.7/random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

Would greatly appreacite help here, thanks :)

**Comment by BrightGu** [comment]
It means the source_file_list is empty? Please check the test_wav_dir or have a debug?
The test_wav_dir can be organized as:
test_wav_dir/
        figure1/
              1.wav
              2.wav
        figure2/
             12.wav
             28.wav
Please try again.
